export interface Contrato {
  id: number;
  rupNo?: string;
  title: string;
  year: number;
  type: string;
  shortDescription: string;
  fullDescription: string;
  tag: string;
  color: string;
  categoria: "ambiental" | "forestal" | "agropecuario" | "territorial";
  entidad?: string;
  municipio?: string;
  imagen: string;
  valor?: number;
  participacion?: number;
  fechaInicio?: string;
  fechaFin?: string;
  duracion?: string;
  smmlv?: number;
  consorcio?: string;
}

// Cada contrato tiene una URL de imagen única de Unsplash
// Las URLs son distintas para que cada card se vea diferente

export const contratos: Contrato[] = [

  // ═══════════════════════════════════════════
  // FORESTAL (29 contratos)
  // ═══════════════════════════════════════════
  {
    id: 1, rupNo: "1",
    title: "Contrato de Obra Pública N° 001 de 2010 — Quipama",
    year: 2010, type: "Obra Pública",
    shortDescription: "Reforestación en zonas de recarga hídrica mediante establecimiento y aislamiento de bosque protector-productor en veredas del Municipio de Quipama.",
    fullDescription: "Contratar por el sistema de precios unitarios la reforestación en las zonas de recarga hídrica de ríos y quebradas mediante el establecimiento y aislamiento de bosque protector-productor en veredas Humbo, Cromal, Tananay, La Vega, Nacabal, Itoco Sur, Itoco Norte, Agua fría, Note, Sorquesito, Parque, Guacay, Sorque Grande, Hachital, Granadilla, Barro Blanco, Balcón, Vereda centro del Municipio de Quipama.",
    tag: "Reforestación", color: "#5a9e2f", categoria: "forestal",
    entidad: "Municipio de Quipama - Boyacá", municipio: "Quipama, Boyacá",
    valor: 748665000, participacion: 100, fechaInicio: "13/12/2010", fechaFin: "09/04/2013", duracion: "2 años 4 meses", smmlv: 1270,
    imagen: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80",
  },
  {
    id: 2, rupNo: "2",
    title: "Contrato de Reforestación No. 193 de 2009 — Guasca",
    year: 2009, type: "Reforestación",
    shortDescription: "Reforestación y mantenimiento de 31 hectáreas en predios de Santa María de las Lagunas, micro cuencas del Río Siecha Aves del Municipio de Guasca.",
    fullDescription: "Reforestación y mantenimiento de 31 hectáreas en los predios de Santa María de las Lagunas, Porvenir, Diamante, Finca San Pedro y las Juntas, ubicadas en las veredas la Concepción y la Trinidad, las micro cuencas del Río Siecha Aves del Municipio de Guasca, cercamiento del área reforestada y sensibilización.",
    tag: "31 ha", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Guasca", municipio: "Guasca, Cundinamarca",
    valor: 103400178, participacion: 100, fechaInicio: "26/05/2009", fechaFin: "26/09/2009", duracion: "4 meses", smmlv: 208.09,
    imagen: "https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?w=600&q=80",
  },
  {
    id: 3, rupNo: "3",
    title: "Contrato UA-OPS 2011-001 — Inventario Refinería Barrancabermeja",
    year: 2011, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal en zona de interés del Proyecto de Modernización de la Refinería de Barrancabermeja, permisos 3-7, y acompañamiento a la Autoridad Ambiental.",
    fullDescription: "Apoyo para el desarrollo del inventario forestal de la nueva zona de interés del proyecto de Modernización de la Refinería de Barrancabermeja, zona externa permiso 6 y 7 y remarcación y actualización permisos 3, 4 y 5, en el marco JOB interno No 463 y acompañamiento de las visitas de la Autoridad Ambiental.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Barrancabermeja, Santander",
    valor: 97515400, participacion: 100, fechaInicio: "12/01/2011", fechaFin: "02/03/2011", duracion: "1.5 meses", smmlv: 182.07,
    imagen: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
  },
  {
    id: 4, rupNo: "4",
    title: "Contrato UA-OPS-041-10 de 2009 — Bosques Cundinamarca",
    year: 2009, type: "Prestación de Servicios",
    shortDescription: "Integración de información técnica forestal y de tierras para la implementación de la Unidad Administrativa Especial Bosques de Cundinamarca.",
    fullDescription: "Integración de toda la información técnica alusiva a los aspectos forestales y de tierras relacionados con el objeto de la propuesta del apoyo para la implementación de la unidad administrativa especial bosques de Cundinamarca.",
    tag: "Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Cundinamarca",
    valor: 4640000, participacion: 100, fechaInicio: "15/10/2009", fechaFin: "15/01/2010", duracion: "3 meses", smmlv: 9.01,
    imagen: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
  },
  {
    id: 5, rupNo: "5",
    title: "Contrato UAOPS-023-08 de 2010 — Inventario Terminal Coveñas",
    year: 2010, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal para ampliación del Terminal Petrolero de Coveñas y elaboración de solicitud de aprovechamiento forestal.",
    fullDescription: "Participación en la elaboración de los estudios ambientales para la ampliación del Terminal Petrolero de Coveñas: Realización del Inventario forestal las áreas a ser intervenidas por las actividades de construcción y elaboración de la solicitud de aprovechamiento forestal.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Coveñas, Sucre",
    valor: 19142900, participacion: 100, fechaInicio: "17/08/2010", fechaFin: "10/09/2010", duracion: "23 días", smmlv: 37.17,
    imagen: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&q=80",
  },
  {
    id: 6, rupNo: "32",
    title: "Contrato No. 020 de 2011 — Reforestación Nobsa",
    year: 2011, type: "Obra",
    shortDescription: "Reforestación protectora de 62 ha, mantenimiento de 197 ha y aislamiento de 22 ha en el Municipio de Nobsa, Departamento Boyacá.",
    fullDescription: "Reforestación protectora de 62ha y mantenimiento de 197ha y aislamiento de 22ha en el Municipio de Nobsa Departamento Boyacá.",
    tag: "281 ha", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Nobsa", municipio: "Nobsa, Boyacá",
    consorcio: "Consorcio Reforestemos Nobsa",
    valor: 402581934, participacion: 80, fechaInicio: "28/09/2011", fechaFin: "28/11/2012", duracion: "14 meses", smmlv: 888,
    imagen: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80",
  },
  {
    id: 7, rupNo: "33",
    title: "Contrato No. 082 de 2009 — Plantaciones Sesquilé",
    year: 2009, type: "Obra",
    shortDescription: "Establecimiento, mantenimiento y aislamiento de plantaciones forestales en veredas Salinas y Boitiva del Municipio de Sesquilé, Cundinamarca.",
    fullDescription: "Realizar el establecimiento, mantenimiento y aislamiento de plantaciones forestales en las veredas Salinas y Boitiva sector la playa del Municipio de Sesquilé - Cundinamarca.",
    tag: "Plantación", color: "#5a9e2f", categoria: "forestal",
    entidad: "Inmobiliaria de Cundinamarca", municipio: "Sesquilé, Cundinamarca",
    consorcio: "Consorcio Reforestemos 2009",
    valor: 55530319, participacion: 50, fechaInicio: "30/11/2009", fechaFin: "09/07/2011", duracion: "1 año 7 meses", smmlv: 103.68,
    imagen: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=600&q=80",
  },
  {
    id: 8, rupNo: "34",
    title: "Contrato de Obra No. 121 de 2011 — Recuperación Fúquene",
    year: 2011, type: "Obra",
    shortDescription: "Recuperación de áreas degradadas mediante reforestación protectora-productora en veredas Chinzaque, Taravita, Nemoga y Centro del Municipio de Fúquene.",
    fullDescription: "Recuperación de áreas degradadas mediante reforestación Protectora, productora en las veredas Chinzaque, Taravita, Nemoga y Centro de Municipio de Fúquene Cundinamarca.",
    tag: "Recuperación", color: "#5a9e2f", categoria: "forestal",
    entidad: "Municipio de Fúquene", municipio: "Fúquene, Cundinamarca",
    valor: 182845964, participacion: 100, fechaInicio: "09/12/2011", fechaFin: "18/06/2013", duracion: "10 meses", smmlv: 310.17,
    imagen: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80",
  },
  {
    id: 9, rupNo: "83",
    title: "Contrato de Obra N° 022 de 2010 — Plantaciones Ubalá",
    year: 2010, type: "Obra Pública",
    shortDescription: "Establecimiento y aislamiento de 15.5 ha (21.700 árboles) de plantaciones forestales protectoras en microcuencas de ríos del Municipio de Ubalá.",
    fullDescription: "Contratar por el sistema de precios unitarios fijos sin fórmula de ajuste, el Establecimiento y aislamiento de (15.5) hectáreas (21.700 árboles) de plantaciones forestales protectoras productoras en las microcuencas de los ríos Zaguea, Trompetas, Chivor, Río Negro y Quebrada el Gusano, así como la construcción de 2.526,5 metros lineales de cerca en alambre de púas, en el municipio de Ubalá.",
    tag: "21.700 árboles", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Ubalá", municipio: "Ubalá, Cundinamarca",
    valor: 45131020, participacion: 100, fechaInicio: "26/11/2010", fechaFin: "26/05/2011", duracion: "6 meses", smmlv: 84.26,
    imagen: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
  },
  {
    id: 10, rupNo: "48",
    title: "Contrato de Obra No. 035 de 2010 — Restauración Botaderos Ubalá",
    year: 2010, type: "Obra",
    shortDescription: "Restauración ambiental en botaderos a cielo abierto en inspecciones de San Pedro de Jagua, Laguna Azul, Santa Rosa y granja municipal de Ubalá.",
    fullDescription: "Contratar la implementación de acciones prioritarias de restauración ambiental en áreas identificadas como botaderos a cielo abierto de las inspecciones de San pedro de Jagua, Laguna azul, Santa Rosa y la granja municipal, ubicadas en el municipio de Ubalá.",
    tag: "Restauración", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Ubalá", municipio: "Ubalá, Cundinamarca",
    valor: 22995500, participacion: 100, fechaInicio: "07/12/2010", fechaFin: "07/02/2011", duracion: "2 meses", smmlv: 42.93,
    imagen: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&q=80",
  },
  {
    id: 11, rupNo: "50",
    title: "Contrato de Obra No. 11 de 2010 — Plantaciones Carmen de Carupa",
    year: 2010, type: "Obra",
    shortDescription: "Establecimiento, mantenimiento y aislamiento de plantaciones forestales en Carmen de Carupa, Cundinamarca, en un área de 25.85 ha.",
    fullDescription: "Establecimiento, mantenimiento y aislamiento de plantaciones forestales, en el municipio de Carmen de Carupa - Cundinamarca, en un área de 25.85ha.",
    tag: "25.85 ha", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Carmen de Carupa", municipio: "Carmen de Carupa, Cundinamarca",
    valor: 190541281, participacion: 100, fechaInicio: "17/08/2010", fechaFin: "30/03/2011", duracion: "7 meses", smmlv: 355.75,
    imagen: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&q=80",
  },
  {
    id: 12, rupNo: "52",
    title: "Contrato de Obra Pública No. 001 de 2010 — San Pablo de Borbur",
    year: 2010, type: "Obra Pública",
    shortDescription: "Reforestación de zonas aledañas a cuencas, microcuencas y nacederos en el ecosistema estratégico del Municipio de San Pablo de Borbur.",
    fullDescription: "Contratar la ejecución de obras de reforestación de zonas aledañas a cuencas, microcuencas y nacederos en el ecosistema estratégico, para el abastecimiento de la Población y procesos productivos (cuenca el Chorreron, Cuenca San Martin, Quebrada Buriburi) del Municipio de San Pablo de Borbur.",
    tag: "Cuencas", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de San Pablo de Borbur", municipio: "San Pablo de Borbur, Boyacá",
    valor: 39749200, participacion: 100, fechaInicio: "07/07/2010", fechaFin: "07/09/2010", duracion: "2 meses", smmlv: 77.18,
    imagen: "https://images.unsplash.com/photo-1511497584788-876760111969?w=600&q=80",
  },
  {
    id: 13, rupNo: "62",
    title: "Contrato de Consultoría de 2008 — Reservas CORPOGUAVIO",
    year: 2008, type: "Consultoría",
    shortDescription: "Formulación de planes estratégicos de administración y manejo de siete áreas de Reserva Forestal Protectora jurisdicción de CORPOGUAVIO.",
    fullDescription: "Formulación de los planes estratégicos de administración y manejo de siete áreas de Reserva Forestal Protectora jurisdicción de CORPOGUAVIO, como actividades específicas realizó el monitoreo de flora y fauna, caracterización de vegetación, análisis y monitoreo de calidad de aguas, componente de capacitación, y la participación en actividades de diagnóstico y formulación del plan.",
    tag: "Reserva Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "2C Ingenieros S.A.", municipio: "Jurisdicción CORPOGUAVIO",
    valor: 60000000, participacion: 100, fechaInicio: "28/10/2008", fechaFin: "27/05/2009", duracion: "7 meses", smmlv: 120.75,
    imagen: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80",
  },
  {
    id: 14, rupNo: "63",
    title: "Contrato de Obra No. 004 de 2015 — Protección Hídrica Fosca",
    year: 2015, type: "Obra",
    shortDescription: "Establecimiento de 500 plántulas y 4.8 ha de protección hídrica del río Sáname en predio San Felipe, Municipio de Fosca.",
    fullDescription: "Establecimiento de 500 Plántulas y primer mantenimiento de 4.8 hectáreas de la zona de protección hídrica del rio Sáname en predio San Felipe, como parte del convenio 035-2013, entre el municipio de Fosca y la Unidad Administrativa especial Bosques de Cundinamarca.",
    tag: "Protección Hídrica", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Fosca", municipio: "Fosca, Cundinamarca",
    valor: 31401794, participacion: 100, fechaInicio: "22/03/2015", fechaFin: "29/12/2015", duracion: "6 meses", smmlv: 48.73,
    imagen: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600&q=80",
  },
  {
    id: 15, rupNo: "56",
    title: "UA-OPS 2014-15 — Permiso de Aprovechamiento Forestal",
    year: 2014, type: "Inventario",
    shortDescription: "Elaboración del inventario forestal, fichas forestales y documentación completa para la obtención del permiso de aprovechamiento forestal.",
    fullDescription: "Elaboración del inventario Forestal y fichas forestales y toda documentación necesaria para la obtención del permiso de aprovechamiento forestal.",
    tag: "Aprovechamiento", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.",
    valor: 2938320, participacion: 100, fechaInicio: "19/07/2014", fechaFin: "19/09/2014", duracion: "2 meses", smmlv: 4.77,
    imagen: "https://images.unsplash.com/photo-1542601906897-eef455a37b14?w=600&q=80",
  },
  {
    id: 16, rupNo: "57",
    title: "TER 2014-01 — Estudio Forestal Predio El Rosal, Medellín",
    year: 2014, type: "Estudio Forestal",
    shortDescription: "Elaboración del Estudio Forestal y Trámite del Permiso de aprovechamiento forestal para el predio El Rosal, ubicado en Medellín, Antioquia.",
    fullDescription: "Elaboración del Estudio Forestal y Trámite de Obtención del Permiso de aprovechamiento forestal, para el predio el Rosal, ubicado en Medellín, Antioquia.",
    tag: "Permiso Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Medellín, Antioquia",
    valor: 9856000, participacion: 100, fechaInicio: "09/07/2014", fechaFin: "09/08/2014", duracion: "1 mes", smmlv: 16,
    imagen: "https://images.unsplash.com/photo-1444664597500-035db93e2323?w=600&q=80",
  },
  {
    id: 17, rupNo: "67",
    title: "Contrato de Consultoría 0445 de 2015 — Interventoría CIF",
    year: 2015, type: "Consultoría",
    shortDescription: "Interventoría de los contratos del certificado de incentivo forestal (CIF) del Ministerio de Agricultura que requieren verificación en campo.",
    fullDescription: "El contratista se compromete con el Ministerio a realizar la interventoría de los contratos del certificado de incentivo forestal - CIF elaborados por el Ministerio de Agricultura y Desarrollo Rural - MADR, que requieran verificación en campo.",
    tag: "Interventoría CIF", color: "#5a9e2f", categoria: "forestal",
    entidad: "Ministerio de Agricultura", consorcio: "Consorcio Forestal CIF 2015",
    valor: 599903280, participacion: 50, fechaInicio: "18/06/2015", fechaFin: "30/12/2015", duracion: "6 meses", smmlv: 931.02,
    imagen: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=80",
  },
  {
    id: 18, rupNo: "69",
    title: "Contrato No. 027-2014 — Plantación Especies Nativas Bojacá",
    year: 2014, type: "Obra",
    shortDescription: "Plantación con especies nativas en predios de importancia hídrica para el Municipio de Bojacá, incluyendo suministro, mano de obra y educación ambiental.",
    fullDescription: "Realizar una Plantación con especies Nativas en predios de importancia Hídrica para el Municipio de Bojaca incluyendo suministro de plantas, mano de obra para la plantación, los insumos, la realización de mantenimiento y gestión - educación ambiental.",
    tag: "Especies Nativas", color: "#5a9e2f", categoria: "forestal",
    entidad: "Alcaldía Municipal de Bojacá", municipio: "Bojacá, Cundinamarca",
    valor: 64731555, participacion: 100, fechaInicio: "02/04/2014", fechaFin: "19/11/2014", duracion: "10 meses", smmlv: 105.08,
    imagen: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=600&q=80",
  },
  {
    id: 19, rupNo: "90",
    title: "Contrato de Obra N° 200-12-08-515 — Mantenimiento CORPOGUAVIO",
    year: 2016, type: "Obra",
    shortDescription: "Dos mantenimientos a plantaciones forestales en municipios de la jurisdicción de CORPOGUAVIO en el marco del fondo de compensación ambiental.",
    fullDescription: "Desarrollar dos mantenimientos a las plantaciones forestales establecida en los municipios de la jurisdicción de la Corporación Autónoma Regional de Guavio - CORPOGUAVIO en el marco del proyecto aprobado por el fondo de compensación Ambiental.",
    tag: "Mantenimiento", color: "#5a9e2f", categoria: "forestal",
    entidad: "CORPOGUAVIO", municipio: "Jurisdicción CORPOGUAVIO",
    consorcio: "Unión Temporal Mantenimientos Ecolinagro",
    valor: 507628211, participacion: 60, fechaInicio: "07/12/2016", fechaFin: "06/10/2017", duracion: "10 meses", smmlv: 688.11,
    imagen: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&q=80",
  },
  {
    id: 20, rupNo: "92",
    title: "EPC-PS-445-2017 — PUEAA Chipaque, Une y Cáqueza",
    year: 2017, type: "Prestación de Servicios",
    shortDescription: "Reforestación, aislamiento y capacitación para el programa de uso eficiente y ahorro del agua (PUEAA) en Chipaque, Une y Cáqueza.",
    fullDescription: "Prestación de servicios para realizar la reforestación, aislamiento y capacitación, para apoyar la implementación del programa de uso eficiente y ahorro del agua - PUEAA en los municipios de Chipaque, Une y Cáqueza del departamento de Cundinamarca.",
    tag: "PUEAA", color: "#5a9e2f", categoria: "forestal",
    entidad: "Empresas Públicas de Cundinamarca", municipio: "Chipaque, Une y Cáqueza",
    valor: 118677304, participacion: 100, fechaInicio: "2017", fechaFin: "2017", duracion: "4 meses", smmlv: 143.31,
    imagen: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=600&q=80",
  },
  {
    id: 21, rupNo: "73",
    title: "Contrato UA-OPS 2011-002 — Inventario Ecopetrol/Ocensa",
    year: 2011, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal para lotes de Ecopetrol, Ocensa y reserva forestal con acompañamiento a visitas de la Autoridad Ambiental. Marco JOB No 594.",
    fullDescription: "Desarrollo del inventario forestal para los lotes de Ecopetrol, Ocensa y de reserva forestal, así como el acompañamiento a las visitas de la Autoridad Ambiental. En el marco JOB interno No 594.",
    tag: "Ecopetrol", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.",
    valor: 22739132, participacion: 100, fechaInicio: "12/01/2011", fechaFin: "07/02/2011", duracion: "25 días", smmlv: 42.45,
    imagen: "https://images.unsplash.com/photo-1539186607079-f60fdf87d134?w=600&q=80",
  },
  {
    id: 22, rupNo: "74",
    title: "Contrato UA-OPS-024-08 de 2010 — Barrancabermeja JOB 463",
    year: 2010, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal para modernización de la Refinería de Barrancabermeja y elaboración de solicitud de permiso de aprovechamiento forestal. Marco JOB 463.",
    fullDescription: "Apoyo para el desarrollo del Inventario forestal de la zona de interés del Proyecto de Modernización de la Refinería de Barrancabermeja para el desarrollo y elaboración de la solicitud de aprovechamiento forestal y acompañamiento a las visitas de la autoridad ambiental. En el marco JOB Interno 463.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Barrancabermeja, Santander",
    valor: 20000000, participacion: 100, fechaInicio: "02/08/2010", fechaFin: "31/08/2010", duracion: "29 días", smmlv: 38.83,
    imagen: "https://images.unsplash.com/photo-1519766304817-4f37bda74a26?w=600&q=80",
  },
  {
    id: 23, rupNo: "75",
    title: "Contrato UAOPS-010-06 de 2010 — Inventario TNP JOB 580",
    year: 2010, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal de áreas a intervenir por ampliación al TNP y elaboración de solicitud de permiso de aprovechamiento forestal. Marco JOB 580.",
    fullDescription: "Inventario forestal de las áreas a ser intervenidas por las actividades de ampliación al TNP y elaboración de la solicitud de permiso de aprovechamiento forestal. En el marco del JOB interno 580.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.",
    valor: 5416040, participacion: 100, fechaInicio: "14/06/2010", fechaFin: "30/07/2010", duracion: "46 días", smmlv: 10.52,
    imagen: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80",
  },
  {
    id: 24, rupNo: "76",
    title: "Contrato UAOPS-039-10-2009 — Inventario Refinería CH 807",
    year: 2009, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal del Proyecto de Modernización de la Refinería de Barrancabermeja. Marco subcontrato No. 164-123939-02-CH 807.",
    fullDescription: "Prestación de servicios con el fin de realizar el Inventario forestal de la zona de interés del Proyecto de Modernización de la Refinería de Barrancabermeja. En el marco del subcontrato No. 164-123939-02-CH 807, y elaboración de la solicitud de permiso de aprovechamiento forestal.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.",
    valor: 6960000, participacion: 100, fechaInicio: "05/10/2009", fechaFin: "31/01/2010", duracion: "4 meses", smmlv: 13.51,
    imagen: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80",
  },
  {
    id: 25, rupNo: "77",
    title: "Contrato UA-OPS 2011-003 — Inventario Puerto Morrosquillo",
    year: 2011, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal para el lote del Puerto de Morrosquillo y acompañamiento a visitas de la Autoridad Ambiental. Marco JOB No 625.",
    fullDescription: "Desarrollo del inventario forestal para el lote correspondiente al Puerto de Morrosquillo, así como el acompañamiento a las visitas de la Autoridad Ambiental. En el marco JOB interno No 625.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Morrosquillo, Sucre",
    valor: 27763788, participacion: 100, fechaInicio: "11/01/2011", fechaFin: "28/02/2011", duracion: "50 días", smmlv: 51.84,
    imagen: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
  },
  {
    id: 26, rupNo: "78",
    title: "Contrato UA-OPS-040-10 de 2009 — Inventario Puerto Bahía Colombia",
    year: 2009, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal del Puerto Bahía Colombia y elaboración de solicitud de permiso de aprovechamiento forestal.",
    fullDescription: "Prestación de servicios con el fin de realizar el Inventario forestal de la zona de interés del Puerto Bahia Colombia, y elaboración de la solicitud de permiso de aprovechamiento forestal.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.",
    valor: 2320000, participacion: 100, fechaInicio: "17/09/2009", fechaFin: "30/11/2009", duracion: "43 días", smmlv: 4.67,
    imagen: "https://images.unsplash.com/photo-1564419320461-6870880221ad?w=600&q=80",
  },
  {
    id: 27, rupNo: "38",
    title: "Contrato UAOPS-2011-008 — Inventario Lote Casa Blanca, Cartagena",
    year: 2011, type: "Prestación de Servicios",
    shortDescription: "Inventario forestal en el lote Casa Blanca (Cartagena) para obtener permiso de aprovechamiento forestal único con acompañamiento de la Autoridad Ambiental.",
    fullDescription: "Integrar la información necesaria para obtener el permiso de aprovechamiento forestal único que se requiere en el lote Casa Blanca (Cartagena). Identificar la fauna asociada a las diferentes unidades de cobertura vegetal y usos del suelo. El servicio incluye la realización del inventario forestal en campo, la elaboración del informe correspondiente y de la solicitud de permiso de aprovechamiento forestal único.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Araújo Ibarra & Asociados S.A.", municipio: "Cartagena, Bolívar",
    valor: 39486400, participacion: 100, fechaInicio: "01/04/2011", fechaFin: "15/04/2011", duracion: "15 días", smmlv: 73.72,
    imagen: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80",
  },
  {
    id: 28, rupNo: "98",
    title: "Orden de Servicios No. 094-2016 — Inventario ZODME'S POB",
    year: 2016, type: "Orden de Servicios",
    shortDescription: "Inventario forestal y documentos para obtención del permiso de aprovechamiento forestal y levantamiento de vedas en zonas de disposición de materiales ZODME'S.",
    fullDescription: "Realizar las actividades de inventario forestal y elaboración de los documentos pertinentes de acuerdo a la normatividad ambiental vigente aplicable para la presentación y obtención del permiso de aprovechamiento forestal y levantamiento de vedas en las zonas de disposición de materiales sobrantes de excavación ZODME'S.",
    tag: "Inventario Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Consorcio Constructor POB (JV-POB)",
    valor: 121800000, participacion: 100, fechaInicio: "08/07/2016", fechaFin: "30/11/2016", duracion: "4 meses", smmlv: 176.66,
    imagen: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=600&q=80",
  },
  {
    id: 29, rupNo: "89",
    title: "Contrato N° 230-2017 — Plan de Ordenación Forestal Atlántico",
    year: 2017, type: "Consultoría",
    shortDescription: "Actividades de campo y oficina para consolidar el plan de ordenación forestal del Departamento del Atlántico conforme a la guía de ordenación forestal sostenible en Colombia.",
    fullDescription: "Adelantar las actividades finales de 'campo' y 'oficina' conforme a la guía para el desarrollo de la ordenación forestal integral y sostenible en Colombia, que permita consolidar el plan de ordenación forestal del departamento del Atlántico, teniendo en cuenta las modificaciones que ha sufrido el territorio en virtud del cambio climático.",
    tag: "Ordenación Forestal", color: "#5a9e2f", categoria: "forestal",
    entidad: "Corporación Autónoma Regional del Atlántico C.R.A.", municipio: "Atlántico",
    valor: 849933700, participacion: 100, fechaInicio: "07/03/2017", fechaFin: "14/03/2018", duracion: "7 meses", smmlv: 1574.33,
    imagen: "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?w=600&q=80",
  },

  // ═══════════════════════════════════════════
  // AMBIENTAL (31 contratos)
  // ═══════════════════════════════════════════
  {
    id: 30, rupNo: "10",
    title: "Contrato N° 0468 de 2010 — Interventoría Cuencas Caquetá",
    year: 2011, type: "Interventoría",
    shortDescription: "Interventoría técnica, administrativa y financiera al proyecto de uso y manejo sostenible en cuencas y microcuencas de 15 municipios de Caquetá.",
    fullDescription: "Interventoría técnica, administrativa y financiera a la ejecución del proyecto: 'Implementación de procesos integrales para el uso y manejo sostenible en cuencas y microcuencas de 15 municipios de Caquetá'.",
    tag: "Interventoría", color: "#00AEEF", categoria: "ambiental",
    entidad: "CORPOAMAZONIA", municipio: "15 municipios de Caquetá",
    valor: 154034544, participacion: 100, fechaInicio: "11/01/2011", fechaFin: "10/02/2012", duracion: "13 meses", smmlv: 271.81,
    imagen: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80",
  },
  {
    id: 31, rupNo: "13",
    title: "Consultoría N° 100-14-4-11-516 — Aceites Lubricantes Casanare",
    year: 2011, type: "Consultoría",
    shortDescription: "Caracterización y propuesta de manejo de aceites lubricantes residuales en municipios del Casanare en el marco del Convenio 031 de 2010.",
    fullDescription: "Caracterización, análisis y propuesta de manejo y acciones correctivas de los aceites lubricantes residuales generados por la actividad socioeconómica en los municipios de Villanueva, Monterrey, Yopal, Aguazul, y Paz de Ariporo del departamento del Casanare en el marco del Convenio 031 de 2010.",
    tag: "Residuos", color: "#00AEEF", categoria: "ambiental",
    entidad: "CORPORINOQUIA", municipio: "Casanare",
    valor: 68970000, participacion: 100, fechaInicio: "10/11/2011", fechaFin: "09/04/2012", duracion: "5 meses", smmlv: 121.70,
    imagen: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&q=80",
  },
  {
    id: 32, rupNo: "14",
    title: "Consultoría N° 100-14-4-11-117 — Páramos Quetame",
    year: 2011, type: "Consultoría",
    shortDescription: "Formulación participativa del plan de manejo ambiental del cordón de páramos El Atravesado, San José y las Burras, Municipio de Quetame.",
    fullDescription: "Realizar la formulación participativa del plan de manejo ambiental del cordón de páramos El Atravesado, San José y las Burras, localizados en el municipio de Quetame, departamento de Cundinamarca jurisdicción de Corporinoquia de acuerdo con las directrices establecidas por la resolución 839 de 2003, proferida por el MAVDT.",
    tag: "Páramos", color: "#00AEEF", categoria: "ambiental",
    entidad: "CORPORINOQUIA", municipio: "Quetame, Cundinamarca",
    valor: 62980500, participacion: 100, fechaInicio: "21/03/2011", fechaFin: "20/08/2011", duracion: "6 meses", smmlv: 117.59,
    imagen: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
  },
  {
    id: 33, rupNo: "16",
    title: "Orden de Servicios No. 801 de 2012 — EIA Bloque Tamarin",
    year: 2012, type: "Orden de Servicios",
    shortDescription: "Estudio de impacto ambiental para la modificación de la licencia ambiental del Bloque Tamarin de Canacol Energy.",
    fullDescription: "Realizar el estudio del impacto ambiental para la modificación de la licencia ambiental del Bloque Tamarin.",
    tag: "Licencia Ambiental", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 131835000, participacion: 100, fechaInicio: "18/01/2012", fechaFin: "15/06/2012", duracion: "4 meses", smmlv: 232.63,
    imagen: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=600&q=80",
  },
  {
    id: 34, rupNo: "17",
    title: "Orden de Servicio No. 805 de 2012 — PMA Rancho Hermoso",
    year: 2012, type: "Orden de Servicios",
    shortDescription: "Plan de Manejo Ambiental para la reubicación de la Planta de Gas del Campo Rancho Hermoso, Departamento del Casanare.",
    fullDescription: "Realización del Plan de Manejo Ambiental para la reubicación de la Planta de Gas del Campo Rancho Hermoso, Departamento del Casanare.",
    tag: "Plan de Manejo", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.", municipio: "Casanare",
    valor: 59491374, participacion: 100, fechaInicio: "24/01/2012", fechaFin: "24/02/2012", duracion: "1 mes", smmlv: 104.98,
    imagen: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
  },
  {
    id: 35, rupNo: "41",
    title: "Consultoría No. 200-12-3-569 de 2009 — Humedales Ubalá/Junín",
    year: 2009, type: "Consultoría",
    shortDescription: "Planes de Manejo Ambiental y monitoreo del complejo de humedales Laguna Verde en Ubalá y complejos al Corbata y Tembladares en Junín.",
    fullDescription: "Formulación participativa de los Planes de Manejo Ambiental y el diseño de los planes de monitoreo del complejo de humedales Laguna Verde en el municipio de Ubalá y los complejos de humedales al Corbata y Tembladares en Junín, Jurisdicción de CORPOGUAVIO.",
    tag: "Humedales", color: "#00AEEF", categoria: "ambiental",
    entidad: "2C Ingenieros S.A.", municipio: "Ubalá y Junín, Cundinamarca",
    valor: 50000000, participacion: 100, fechaInicio: "06/02/2009", fechaFin: "05/09/2009", duracion: "7 meses", smmlv: 100.62,
    imagen: "https://images.unsplash.com/photo-1582560475093-ba66accbc095?w=600&q=80",
  },
  {
    id: 36, rupNo: "42",
    title: "Consultoría No. 200-12-18-478 — Humedales Gachetá",
    year: 2010, type: "Consultoría",
    shortDescription: "Plan de Manejo Ambiental del complejo de humedales de la cuenca alta de la quebrada Las Pavas en la vereda Muchindote, Municipio de Gachetá.",
    fullDescription: "Formulación del Plan de Manejo Ambiental del complejo de humedales de la cuenca alta de la quebrada las Pavas en la vereda Muchindote, en el municipio de Gachetá, Jurisdicción de CORPOGUAVIO.",
    tag: "Humedales", color: "#00AEEF", categoria: "ambiental",
    entidad: "2C Ingenieros S.A.", municipio: "Gachetá, Cundinamarca",
    valor: 25000000, participacion: 100, fechaInicio: "02/02/2010", fechaFin: "01/06/2010", duracion: "4 meses", smmlv: 48.54,
    imagen: "https://images.unsplash.com/photo-1569748101973-e5553a4f1439?w=600&q=80",
  },
  {
    id: 37, rupNo: "35",
    title: "Prestación de Servicios N° 0082 de 2011 — Interventoría CORPOAMAZONIA",
    year: 2011, type: "Interventoría",
    shortDescription: "Interventoría técnica, administrativa y financiera del proyecto de sistemas agroecológicos sostenibles y repoblamiento forestal en comunidades indígenas del Caquetá.",
    fullDescription: "Interventoría técnica, administrativa, y financiera del proyecto de inversión: 'Implementación de sistemas agroecológicos sostenibles y repoblamiento forestal en áreas degradadas en comunidades indígenas en el departamento de Caquetá'.",
    tag: "Interventoría", color: "#00AEEF", categoria: "ambiental",
    entidad: "CORPOAMAZONIA", municipio: "Caquetá",
    valor: 43786520, participacion: 100, fechaInicio: "05/04/2011", fechaFin: "05/02/2012", duracion: "10 meses", smmlv: 77.27,
    imagen: "https://images.unsplash.com/photo-1621859758285-e61e6bdab55c?w=600&q=80",
  },
  {
    id: 38, rupNo: "39",
    title: "Orden de Servicio N. 58 de 2012 — PMA Pozo Portofino A",
    year: 2012, type: "Orden de Servicios",
    shortDescription: "Plan de Manejo Ambiental del Pozo estratigráfico Portofino A de Canacol Energy.",
    fullDescription: "Realizar el Plan de Manejo Ambiental del Pozo estratigráfico Portofino A.",
    tag: "Pozo Estratigráfico", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 59189000, participacion: 100, fechaInicio: "02/05/2012", fechaFin: "27/05/2012", duracion: "25 días", smmlv: 104.45,
    imagen: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80",
  },
  {
    id: 39, rupNo: "40",
    title: "Orden de Servicios No. 064 de 2011 — Recuperación Recio 1 y 2",
    year: 2011, type: "Orden de Servicios",
    shortDescription: "Sostenimiento de la recuperación ambiental de Recio 1 y 2 — 1200 árboles y zona de pastos, replante durante 10 meses.",
    fullDescription: "Sostenimiento de la recuperación ambiental de Recio 1 y 2 comprendida por 1200 árboles y zona de pastos, además de replantar los árboles perdidos durante 10 meses, MANO DE OBRA, INSUMOS, COSTOS INDIRECTOS.",
    tag: "Recuperación", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 24920000, participacion: 100, fechaInicio: "22/07/2011", fechaFin: "22/05/2012", duracion: "10 meses", smmlv: 43.97,
    imagen: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
  },
  {
    id: 40, rupNo: "79",
    title: "CEC-0278 — PMA Plataforma Rancho Hermoso 9",
    year: 2011, type: "Consultoría",
    shortDescription: "Actualización de los planes de manejo ambiental para la plataforma multipozo Rancho Hermoso 9 de Canacol Energy.",
    fullDescription: "Actualización de los planes de manejo ambiental para la plataformas multipozo rancho hermoso 9.",
    tag: "PMA", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 22376400, participacion: 100, fechaInicio: "24/06/2011", fechaFin: "24/07/2011", duracion: "30 días", smmlv: 41.78,
    imagen: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600&q=80",
  },
  {
    id: 41, rupNo: "80",
    title: "CEC-0279 — PMA Plataforma Rancho Hermoso 4",
    year: 2011, type: "Consultoría",
    shortDescription: "Actualización de los planes de manejo ambiental para la plataforma multipozo Rancho Hermoso 4 de Canacol Energy.",
    fullDescription: "Actualización de los planes de manejo ambiental para la plataformas multipozo rancho hermoso 4.",
    tag: "PMA", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 25005733, participacion: 100, fechaInicio: "23/06/2011", fechaFin: "21/07/2011", duracion: "30 días", smmlv: 46.69,
    imagen: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=600&q=80",
  },
  {
    id: 42, rupNo: "81",
    title: "Orden de Servicios No. 1043 de 2012 — PMA Rancho Hermoso 3",
    year: 2012, type: "Orden de Servicios",
    shortDescription: "Actualización del PMA de la plataforma Rancho Hermoso 3 (RH3) cumpliendo los HTER 310 del Ministerio de Medio Ambiente.",
    fullDescription: "Actualización del plan de manejo ambiental de la plataforma Rancho Hermoso 3 (RH3) cumpliendo los HTER 310 expedidos por el ministerio de medio ambiente y desarrollo sostenible (Personal, Cartografía y gastos de Campo).",
    tag: "PMA", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 16479540, participacion: 100, fechaInicio: "18/04/2012", fechaFin: "08/05/2012", duracion: "1 mes", smmlv: 29.08,
    imagen: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=80",
  },
  {
    id: 43, rupNo: "82",
    title: "Orden de Servicios No. 1044 de 2012 — PMA Rancho Hermoso 9",
    year: 2012, type: "Orden de Servicios",
    shortDescription: "Actualización del PMA de la plataforma Ancho Hermoso 9 (RH 9) cumpliendo los HTER 310 del Ministerio de Medio Ambiente.",
    fullDescription: "Actualización del plan de manejo ambiental de la plataforma ancho Hermoso 9 (RH 9) cumpliendo los HTER 310 expedidos por el ministerio de medio ambiente y desarrollo sostenible (Personal, Cartografía y gastos de Campo).",
    tag: "PMA", color: "#00AEEF", categoria: "ambiental",
    entidad: "Canacol Energy S.A.",
    valor: 16479540, participacion: 100, fechaInicio: "18/04/2012", fechaFin: "08/05/2012", duracion: "1 mes", smmlv: 29.08,
    imagen: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80",
  },
  {
    id: 44, rupNo: "51",
    title: "Consultoría No. 338 de 2009 — Diagnóstico Ambiental Tocancipá",
    year: 2010, type: "Consultoría",
    shortDescription: "Diagnóstico Ambiental de la industria manufacturera y agroindustria en el marco del plan ambiental de reforestación y el SIGAM, Municipio de Tocancipá.",
    fullDescription: "Elaboración del Diagnóstico Ambiental de la industria manufacturera y agroindustria en el marco del plan ambiental de reforestación y el SIGAM, en el Municipio de Tocancipá.",
    tag: "Diagnóstico", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Municipal de Tocancipá", municipio: "Tocancipá, Cundinamarca",
    valor: 12702000, participacion: 100, fechaInicio: "19/01/2010", fechaFin: "03/06/2010", duracion: "3 meses", smmlv: 24.66,
    imagen: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=600&q=80",
  },
  {
    id: 45, rupNo: "53",
    title: "Orden de Servicios No. 9936 — Inventario Vía CAPELLA J52",
    year: 2014, type: "Orden de Servicios",
    shortDescription: "Inventario Forestal al 100% de aproximadamente 14.400 m² en la vía de acceso hacia el Proyecto CAPELLA J52, Departamento del Caquetá.",
    fullDescription: "Elaboración del inventario Forestal al 100% de aproximadamente 14,400 m^2, en un trazado de la vía de acceso hacia el Proyecto CAPELLA J52 en el Departamento del Caquetá.",
    tag: "CAPELLA J52", color: "#00AEEF", categoria: "ambiental",
    entidad: "Emerald Energy", municipio: "Caquetá",
    valor: 23869688, participacion: 100, fechaInicio: "17/02/2014", fechaFin: "16/03/2014", duracion: "1 mes", smmlv: 38.73,
    imagen: "https://images.unsplash.com/photo-1519766304817-4f37bda74a26?w=600&q=80",
  },
  {
    id: 46, rupNo: "54",
    title: "Orden de Servicios N° 9658 de 2013 — PMA Capella J52",
    year: 2013, type: "Orden de Servicios",
    shortDescription: "Actualización del Plan de Manejo Ambiental de la Plataforma Multipozo Capella J 52 del campo Capella, Departamento de Caquetá.",
    fullDescription: "Actualización del Plan de manejo ambiental (PMA) de la Plataforma Multipozo Capella J 52- del campo Capella, ubicado en el departamento de Caquetá.",
    tag: "PMA", color: "#00AEEF", categoria: "ambiental",
    entidad: "Emerald Energy", municipio: "Caquetá",
    valor: 42555946, participacion: 100, fechaInicio: "13/06/2013", fechaFin: "12/08/2013", duracion: "2 meses", smmlv: 72.19,
    imagen: "https://images.unsplash.com/photo-1476362174823-3a23f4aa6d76?w=600&q=80",
  },
  {
    id: 47, rupNo: "36",
    title: "Prestación de Servicios No. 037-2013 — PGIRS Susa",
    year: 2013, type: "Prestación de Servicios",
    shortDescription: "Actualización del Plan de Gestión Integral de Residuos Sólidos para el municipio de Susa, Cundinamarca.",
    fullDescription: "Actualización de Plan de Gestión Integral de Residuos Sólidos para el municipio de Susa - PGIRS Susa Cundinamarca.",
    tag: "PGIRS", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Susa Cundinamarca", municipio: "Susa, Cundinamarca",
    valor: 10480647, participacion: 100, fechaInicio: "17/05/2013", fechaFin: "16/10/2013", duracion: "5 meses", smmlv: 17.78,
    imagen: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&q=80",
  },
  {
    id: 48, rupNo: "61",
    title: "Contrato No. 136 de 2015 — PGIRS Ubalá Zonas A y B",
    year: 2015, type: "Prestación de Servicios",
    shortDescription: "Actualización del PGIRS del municipio de Ubalá, zonas A y B, acorde con el decreto 2981 de 2013 y la resolución 0754 de 2014.",
    fullDescription: "Prestación de servicios profesionales para realizar la actualización del plan de gestión integral de residuos sólidos (PGIRS) acorde con el decreto 2981 de 2013 y la resolución 0754 de 2014, en el municipio de Ubalá, zonas A y B.",
    tag: "PGIRS", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Municipal de Ubalá", municipio: "Ubalá, Cundinamarca",
    valor: 50000000, participacion: 100, fechaInicio: "09/10/2015", fechaFin: "29/12/2015", duracion: "2 meses", smmlv: 77.60,
    imagen: "https://images.unsplash.com/photo-1526951521990-620dc14c214b?w=600&q=80",
  },
  {
    id: 49, rupNo: "65",
    title: "Consultoría No. 0199 de 2015 — PGIRS La Vega",
    year: 2015, type: "Consultoría",
    shortDescription: "Actualización del PGIRS del Municipio de La Vega acorde con el decreto 2981 de 2003 y la resolución 0754 de 2014.",
    fullDescription: "Apoyo para la actualización del plan de gestión Integral de residuos sólidos-PGIRS del Municipio de la Vega acorde con el decreto 2981 de 2003 y la resolución 0754 de 2014.",
    tag: "PGIRS", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Municipal de La Vega", municipio: "La Vega, Cundinamarca",
    valor: 49764000, participacion: 100, fechaInicio: "29/10/2015", fechaFin: "19/12/2015", duracion: "45 días", smmlv: 77.23,
    imagen: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
  },
  {
    id: 50, rupNo: "71",
    title: "Contrato No. 0000358 de 2015 — Observatorio Ambiental Atlántico",
    year: 2016, type: "Consultoría",
    shortDescription: "Diseño de un observatorio ambiental para el Departamento del Atlántico para generar sistemas de información confiables e interactivos de apoyo a políticas ambientales.",
    fullDescription: "Adelantar los estudios de diseño de un observatorio ambiental para el departamento del Atlántico como estrategia principal para generar sistemas de información confiables e interactivos, que apoyen una toma de decisiones más oportuna y acertada en el campo de las políticas y acciones ambientales en el departamento del Atlántico.",
    tag: "Observatorio", color: "#00AEEF", categoria: "ambiental",
    entidad: "Corporación Autónoma Regional del Atlántico – C.R.A.", municipio: "Atlántico",
    valor: 375000000, participacion: 100, fechaInicio: "05/10/2016", fechaFin: "04/02/2017", duracion: "4 meses", smmlv: 543.91,
    imagen: "https://images.unsplash.com/photo-1532094349884-543559059b89?w=600&q=80",
  },
  {
    id: 51, rupNo: "97",
    title: "Compensación Ambiental — SK Innovation Co. Ltd.",
    year: 2013, type: "Compensación",
    shortDescription: "Compensación ambiental por reforestación derivada de licencia de perforación — 42.21 ha en Paratebueno, Puerto López y Cabuyaro durante 3 años.",
    fullDescription: "Ejecutar la compensación ambiental relacionada con reforestaciones por intervención de cobertura y cambio de uso del suelo, derivados de la licencia ambiental de los proyectos de perforación, ejecutará el aislamiento, establecimiento y mantenimiento por tres años de 42,21 ha en los municipios de Paratebueno (Cundinamarca), Puerto López y Cabuyaro (Meta).",
    tag: "42.21 ha", color: "#00AEEF", categoria: "ambiental",
    entidad: "SK Innovation Co. Ltd.", municipio: "Paratebueno, Puerto López, Cabuyaro",
    valor: 699442926, participacion: 100, fechaInicio: "11/01/2013", fechaFin: "11/01/2016", duracion: "36 meses",
    imagen: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80",
  },
  {
    id: 52, rupNo: "96",
    title: "Servicio de Rehabilitación Ambiental 4400006195 — GeoPark",
    year: 2013, type: "Rehabilitación",
    shortDescription: "Compensación ambiental por reforestaciones derivadas de licencia de proyectos de perforación — 42.21 ha en Cundinamarca y Meta. GeoPark Colombia.",
    fullDescription: "Ejecutar la compensación ambiental relacionada con reforestaciones por intervención de cobertura y cambio de uso del suelo, derivados de la licencia ambiental de los proyectos de perforación, por lo cual, ejecutará el aislamiento, establecimiento y mantenimiento por tres años de 42,21 ha en los municipios de Paratebueno (Cundinamarca), Puerto López y Cabuyaro (Meta).",
    tag: "Rehabilitación", color: "#00AEEF", categoria: "ambiental",
    entidad: "GeoPark Colombia SAS", municipio: "Paratebueno, Puerto López, Cabuyaro",
    valor: 136216801, participacion: 100, fechaInicio: "11/01/2013", fechaFin: "11/01/2016", duracion: "36 meses", smmlv: 164.49,
    imagen: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=600&q=80",
  },
  {
    id: 53, rupNo: "11",
    title: "Contrato PSGGCT-2.7.12-498 — Interventoría Agroforestal Meta",
    year: 2013, type: "Interventoría",
    shortDescription: "Interventoría técnica, administrativa y financiera al proyecto de sistemas agroforestales y silvopastoriles en fincas del área de influencia del río Guayuriba, Meta.",
    fullDescription: "Realizar la interventoría técnica, administrativa y financiera al contrato derivado del proyecto de establecimiento de 10 parcelas piloto de sistemas agroforestales y 10 parcelas de sistemas silvopastoriles en fincas ganaderas del área de influencia del río Guayuriba en el departamento del Meta.",
    tag: "Interventoría", color: "#00AEEF", categoria: "ambiental",
    entidad: "CORMACARENA", municipio: "Meta",
    valor: 27913950, participacion: 100, fechaInicio: "19/07/2013", fechaFin: "18/04/2014", duracion: "9 meses", smmlv: 45.31,
    imagen: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
  },
  {
    id: 54, rupNo: "15",
    title: "Orden de Servicio N°. 214 de 2011 — Flujos de Agua UMNG Cajicá",
    year: 2011, type: "Orden de Servicios",
    shortDescription: "Evaluación y caracterización de flujos de agua del campus universitario Cajicá — elaboración del Informe y Materiales para la Universidad Militar Nueva Granada.",
    fullDescription: "Evaluación y caracterización de flujos de agua de las instalaciones del campus universitario Cajicá, Elaboración del Informe, Materiales.",
    tag: "Calidad Agua", color: "#00AEEF", categoria: "ambiental",
    entidad: "Universidad Militar Nueva Granada", municipio: "Cajicá, Cundinamarca",
    valor: 13916892, participacion: 100, fechaInicio: "21/05/2011", fechaFin: "21/07/2011", duracion: "2 meses", smmlv: 25.98,
    imagen: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=600&q=80",
  },
  {
    id: 55, rupNo: "47",
    title: "Contrato PS 064-2009 — PMA y PGIRS Botaderos Ubalá",
    year: 2009, type: "Prestación de Servicios",
    shortDescription: "Elaboración del Plan de Manejo Ambiental de cierre, clausura, saneamiento de botaderos a cielo abierto y PGIRS en el municipio de Ubalá.",
    fullDescription: "Prestación de servicios para la elaboración del Plan de Manejo Ambiental de cierre, clausura saneamiento de botaderos a cielo abierto y PGIRS, en el municipio de Ubalá.",
    tag: "PMA", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Municipal de Ubalá", municipio: "Ubalá, Cundinamarca",
    valor: 13900000, participacion: 100, fechaInicio: "01/09/2009", fechaFin: "01/11/2009", duracion: "2 meses", smmlv: 27.97,
    imagen: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=600&q=80",
  },
  {
    id: 56, rupNo: "72-91",
    title: "Contrato No. 150 de 2015 — PSMV Inspecciones Ubalá",
    year: 2015, type: "Prestación de Servicios",
    shortDescription: "Elaboración del Plan de Saneamiento y Manejo de Vertimientos (PSMV) de Inspecciones de Laguna Azúl Santa Roa y La Playa del Municipio de Ubalá.",
    fullDescription: "Prestación de servicios para la elaboración de los documentos del Plan de Saneamiento y Manejo de Vertimientos - PSMV de las Inspecciones de Laguna Azúl Santa Roa y la Playa del Municipio de Ubalá Cundinamarca, Acorde con la Resolución 1433 de 2004 y demás normas vigentes.",
    tag: "PSMV", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Municipal de Ubalá", municipio: "Ubalá, Cundinamarca",
    valor: 50000000, participacion: 100, fechaInicio: "14/12/2015", fechaFin: "03/04/2016", duracion: "1 mes", smmlv: 72.52,
    imagen: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600&q=80",
  },
  {
    id: 57, rupNo: "19 y 43",
    title: "Orden de Servicios N° 2090690006 — Gestión Ambiental DAS",
    year: 2010, type: "Orden de Servicios",
    shortDescription: "Desarrollo del programa de gestión ambiental del Departamento Administrativo de Seguridad DAS a través de Jardine Lloyd Thompson.",
    fullDescription: "Desarrollo del programa de gestión ambiental del Departamento Administrativo de Seguridad DAS.",
    tag: "Gestión Ambiental", color: "#00AEEF", categoria: "ambiental",
    entidad: "Jardine Lloyd Thompson - BIO",
    valor: 47139500, participacion: 100, fechaInicio: "12/03/2010", fechaFin: "12/11/2010", duracion: "9 meses", smmlv: 91.53,
    imagen: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&q=80",
  },
  {
    id: 58, rupNo: "29",
    title: "Prestación de Servicios 085-2012 — Lodos IPSE Leticia",
    year: 2012, type: "Prestación de Servicios",
    shortDescription: "Diagnóstico y propuesta de manejo de lodos residuales en el tanque de almacenamiento de Fuel Oil de la central de energía de Leticia, Amazona.",
    fullDescription: "Prestar los Servicios para determinar el volumen, diagnóstico y propuesta de manejo de los lodos residuales existentes dentro del tanque de almacenamiento de Fuel Oil en la central de Generación de Energía de Leticia (Amazona).",
    tag: "Residuos", color: "#00AEEF", categoria: "ambiental",
    entidad: "Instituto de Planificación y Promoción de Soluciones Energéticas IPSE", municipio: "Leticia, Amazonas",
    valor: 15428000, participacion: 100, fechaInicio: "25/10/2012", fechaFin: "06/12/2012", duracion: "1 mes", smmlv: 27.22,
    imagen: "https://images.unsplash.com/photo-1498855926480-d98e83099315?w=600&q=80",
  },
  {
    id: 59, rupNo: "95",
    title: "Orden de Servicio — PNUD Marco Ambiental Materiales",
    year: 2017, type: "Orden de Servicios",
    shortDescription: "Fortalecimiento del proyecto de un marco general técnico y ambiental para mejorar la gestión operativa de proyectos de explotación de materiales de construcción.",
    fullDescription: "Fortalecimiento del proyecto de desarrollo de un marco general técnico y ambiental para mejorar la gestión operativa de proyectos de explotación de materiales de construcción.",
    tag: "PNUD", color: "#00AEEF", categoria: "ambiental",
    entidad: "Programa de las Naciones Unidas para el Desarrollo - PNUD",
    valor: 30999500, participacion: 100,
    imagen: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
  },
  {
    id: 60, rupNo: "93",
    title: "Consultoría No. 159 de 2018 — Permiso de Vertimientos PTAR La Vega",
    year: 2018, type: "Consultoría",
    shortDescription: "Estudio de caracterización de vertimientos para el trámite de permiso de vertimientos para la PTAR del municipio de La Vega, Cundinamarca.",
    fullDescription: "Realizar el estudio de caracterización de vertimientos para el trámite de permiso de vertimientos para la PTAR del municipio de La Vega - Cundinamarca.",
    tag: "Vertimientos", color: "#00AEEF", categoria: "ambiental",
    entidad: "Alcaldía Municipal de La Vega", municipio: "La Vega, Cundinamarca",
    valor: 21300000, participacion: 100, fechaInicio: "04/09/2018", fechaFin: "18/12/2018", duracion: "3 meses", smmlv: 75.50,
    imagen: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=600&q=80",
  },

  // ═══════════════════════════════════════════
  // AGROPECUARIO (21 contratos)
  // ═══════════════════════════════════════════
  {
    id: 61, rupNo: "6",
    title: "Contrato de Obra Pública No. 009 de 2011 — Silvopastoril Carmen de Carupa",
    year: 2011, type: "Obra Pública",
    shortDescription: "Implementación de modelos silvopastoriles y agroforestales para recuperación y estabilización de suelos en la zona de ladera de Carmen de Carupa.",
    fullDescription: "Implementación de modelos silvopastoriles y Agroforestales para la recuperación y estabilización de suelos dentro del componente productivo en la zona de ladera del municipio de Carmen de Carupa del departamento de Cundinamarca.",
    tag: "Silvopastoril", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Carmen de Carupa", municipio: "Carmen de Carupa, Cundinamarca",
    valor: 150259000, participacion: 100, fechaInicio: "20/06/2011", fechaFin: "20/06/2012", duracion: "12 meses", smmlv: 265.15,
    imagen: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
  },
  {
    id: 62, rupNo: "55",
    title: "Selección Abreviada SDE 002 de 2009 — Modelos Productivos Cucunuba",
    year: 2009, type: "Obra",
    shortDescription: "Implementación de 32 modelos de restauración y recuperación del componente productivo en la zona rural del municipio de Cucunuba.",
    fullDescription: "Implementación de 32 modelos de restauración y recuperación del componente productivo en la zona rural del municipio de Cucunuba.",
    tag: "Modelos Productivos", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Cucunuba", municipio: "Cucunuba, Cundinamarca",
    consorcio: "Consorcio Reforestemos Cucunuba",
    valor: 109418712, participacion: 50, fechaInicio: "24/07/2009", fechaFin: "24/01/2010", duracion: "6 meses", smmlv: 106.23,
    imagen: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80",
  },
  {
    id: 63, rupNo: "23",
    title: "Contrato de Obra No. 168 de 2009 — Semiestabulación Gachalá",
    year: 2008, type: "Obra",
    shortDescription: "Establecimiento de unidades productivas de semiestabulación y parcelas silvopastoril en el Municipio de Gachalá, Cundinamarca.",
    fullDescription: "Adelantar el establecimiento de unidades productivas de semiestabulación y parcelas silvopastoril en el Municipio de Gachalá, Cundinamarca.",
    tag: "Semiestabulación", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachalá", municipio: "Gachalá, Cundinamarca",
    consorcio: "Consorcio Constructores Gachalá",
    valor: 304807312, participacion: 50, fechaInicio: "02/12/2008", fechaFin: "02/08/2009", duracion: "11 meses", smmlv: 613.42,
    imagen: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600&q=80",
  },
  {
    id: 64, rupNo: "24",
    title: "Prestación de Servicios No. 036 de 2008 — Inseminación Artificial Gachalá",
    year: 2008, type: "Prestación de Servicios",
    shortDescription: "Sincronización e inseminación artificial de 100 hembras aptas reproductivamente en el Municipio de Gachalá, Cundinamarca.",
    fullDescription: "Prestación de servicios para la sincronización e inseminación artificial de 100 hembras aptas reproductivamente en el Municipio de Gachalá Cundinamarca.",
    tag: "Mejoramiento Genético", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachalá", municipio: "Gachalá, Cundinamarca",
    valor: 10000000, participacion: 100, fechaInicio: "02/07/2008", fechaFin: "23/10/2008", duracion: "3 meses 25 días", smmlv: 21.67,
    imagen: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600&q=80",
  },
  {
    id: 65, rupNo: "25",
    title: "Prestación de Servicios No. 037 de 2008 — Planta Sacrificio Gachalá",
    year: 2008, type: "Prestación de Servicios",
    shortDescription: "Asesoría profesional para la formulación del plan gradual de cumplimiento de la planta de sacrificio municipal del Municipio de Gachalá.",
    fullDescription: "Prestación de servicios de asesoría profesional para la formulación del plan gradual de cumplimiento de la planta de sacrificio municipal del Municipio de Gachalá, Cundinamarca.",
    tag: "Pecuario", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachalá", municipio: "Gachalá, Cundinamarca",
    valor: 18000000, participacion: 100, fechaInicio: "02/07/2008", fechaFin: "28/10/2008", duracion: "3 meses", smmlv: 39,
    imagen: "https://images.unsplash.com/photo-1540714234-ec3a5f3a37c9?w=600&q=80",
  },
  {
    id: 66, rupNo: "22",
    title: "Contrato de Suministro No. 148 de 2009 — Insumos Agrícolas Gachalá",
    year: 2009, type: "Suministro",
    shortDescription: "Suministro de implementos e insumos agrícolas para establecimiento del cultivo de frijol variedad bolo rojo y sabanero en veredas de Gachalá.",
    fullDescription: "Suministro de implementos e insumos agrícolas para el establecimiento del cultivo de frijol variedad bolo rojo y sabanero, en las veredas piedra gorda, Chinchorro, Guacamayas, El escobal, La florida y San Isidro del municipio de Gachalá.",
    tag: "Insumos Agrícolas", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachalá", municipio: "Gachalá, Cundinamarca",
    valor: 43617490, participacion: 100, fechaInicio: "28/09/2009", fechaFin: "28/10/2009", duracion: "1 mes", smmlv: 87.78,
    imagen: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=600&q=80",
  },
  {
    id: 67, rupNo: "58",
    title: "Contrato de Suministro No. 261-2014 — Ganadería Víctimas Gachalá",
    year: 2015, type: "Suministro",
    shortDescription: "Suministro de Ganado Bovino, aves de corral e insumos pecuarios para proyectos productivos de atención a víctimas del conflicto, Municipio de Gachalá.",
    fullDescription: "Suministros de Ganado Bovino, aves de corral y equipos e insumos pecuarios para el desarrollo de proyectos productivos en atención de la población víctima del conflicto armado en el Municipio de Gachalá, Cundinamarca.",
    tag: "Ganadería", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachalá", municipio: "Gachalá, Cundinamarca",
    valor: 53255000, participacion: 100, fechaInicio: "22/01/2015", fechaFin: "21/03/2015", duracion: "2 meses", smmlv: 82.65,
    imagen: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=600&q=80",
  },
  {
    id: 68, rupNo: "45",
    title: "Proyecto 5132 — Asistencia Técnica Ciudad Bolívar",
    year: 2007, type: "Proyecto",
    shortDescription: "Asistencia técnica pecuaria, rural y ambiental de la localidad de Ciudad Bolívar articulada a proyectos integrales y diversificación productiva comunitaria.",
    fullDescription: "Dirección y Coordinación Administrativa y Financiera de la interventoría al convenio interadministrativo y de cooperación técnico científica, suscrito entre el DAMA - CORPOICA y el FONDO DE DESARROLLO LOCAL CIUDAD BOLIVAR, mediante el cual ejecuta el proyecto 5132: asistencia técnica pecuaria, rural y ambiental de la localidad de Ciudad Bolívar.",
    tag: "Asistencia Técnica", color: "#b45309", categoria: "agropecuario",
    entidad: "2C Ingenieros S.A. / DAMA-CORPOICA", municipio: "Ciudad Bolívar, Bogotá",
    valor: 55000000, participacion: 100, fechaInicio: "28/08/2007", fechaFin: "28/10/2008", duracion: "14 meses", smmlv: 119.18,
    imagen: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80",
  },
  {
    id: 69, rupNo: "46 y 68",
    title: "Proceso Mínima Cuantía SMC-036-2014 — Compensación CO₂ Gachetá",
    year: 2014, type: "Establecimiento Forestal",
    shortDescription: "Establecimiento forestal para la compensación de las emisiones de dióxido de carbono del municipio de Gachetá en el año 2013.",
    fullDescription: "Establecimiento Forestal como medida para la compensación de las emisiones de dióxido de carbono realizadas por el municipio de Gachetá en el año 2013.",
    tag: "Compensación CO₂", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 4800000, participacion: 100, fechaInicio: "16/10/2014", fechaFin: "31/12/2014", duracion: "2 meses 15 días", smmlv: 7.79,
    imagen: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&q=80",
  },
  {
    id: 70, rupNo: "26",
    title: "Contrato de Compraventa No. 151-2013 — Semillas Seguridad Alimentaria Gachetá",
    year: 2013, type: "Compraventa",
    shortDescription: "Suministro de Insumos (Semillas) para el plan de Seguridad Alimentaria 2013 en el Municipio de Gachetá.",
    fullDescription: "Suministro de Insumos (Semillas) para ser entregados dentro del ciclo de capacitaciones en Desarrollo del plan de Seguridad Alimentaria 2013 en el Municipio de Gachetá.",
    tag: "Seguridad Alimentaria", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 3529000, participacion: 100, fechaInicio: "15/11/2013", fechaFin: "16/12/2013", duracion: "1 mes", smmlv: 5.99,
    imagen: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&q=80",
  },
  {
    id: 71, rupNo: "27",
    title: "Contrato de Compraventa No. 113-2013 — Gallinas Ponedoras Gachetá",
    year: 2013, type: "Compraventa",
    shortDescription: "Proyecto productivo de gallinas ponedoras para la producción de huevo como plan de seguridad alimentaria de familias desplazadas en Gachetá.",
    fullDescription: "Compraventa para el desarrollo del proyecto productivo de gallinas ponedoras para la producción de huevo como plan de seguridad alimentaria de las familias desplazadas residentes en el municipio de Gachetá, Cundinamarca.",
    tag: "Producción Huevo", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 10972656, participacion: 100, fechaInicio: "22/12/2013", fechaFin: "25/02/2014", duracion: "2 meses", smmlv: 17.81,
    imagen: "https://images.unsplash.com/photo-1585300369164-c0c75e1eef97?w=600&q=80",
  },
  {
    id: 72, rupNo: "28",
    title: "Contrato de Compraventa No. 150-2013 — Concentrados Granja Gachetá",
    year: 2013, type: "Compraventa",
    shortDescription: "Compraventa de alimentos concentrados balanceados y suplementarios alimenticios para los animales de la granja integral del Municipio de Gachetá.",
    fullDescription: "Compraventa de alimentos concentrados balanceados y suplementarios alimenticios para los animales de la granja integral del Municipio de Gachetá.",
    tag: "Alimentación Animal", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 6045880, participacion: 100, fechaInicio: "20/11/2013", fechaFin: "29/12/2013", duracion: "1 mes", smmlv: 10.26,
    imagen: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600&q=80",
  },
  {
    id: 73, rupNo: "21",
    title: "Orden de Servicios N° OS1328 — Abandono Pozo Puinaves-2",
    year: 2011, type: "Orden de Servicios",
    shortDescription: "Obras civiles para el abandono del pozo Puinaves-2 en la jurisdicción del municipio de Paz de Ariporo, Casanare. Petrolifera Petroleum.",
    fullDescription: "Servicio de obras civiles para el abandono del pozo Puinaves - 2, ubicado en la jurisdicción del municipio de Paz de Ariporo, Casanare.",
    tag: "Abandono Pozo", color: "#b45309", categoria: "agropecuario",
    entidad: "Petrolifera Petroleum Colombia", municipio: "Paz de Ariporo, Casanare",
    valor: 28081250, participacion: 100, fechaInicio: "31/03/2011", fechaFin: "09/04/2011", duracion: "9 días", smmlv: 52.43,
    imagen: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80",
  },
  {
    id: 74, rupNo: "8",
    title: "Aceptación de Oferta — Mantenimiento Villa Alsacia",
    year: 2012, type: "Servicios",
    shortDescription: "Servicios para el mantenimiento de zonas de cesión al distrito Villa Alsacia etapas 3 y 4, Bienes y Comercio S.A.",
    fullDescription: "Servicios para el mantenimiento zonas de cesión al distrito Villa Alsacia etapas 3 y 4.",
    tag: "Mantenimiento", color: "#b45309", categoria: "agropecuario",
    entidad: "Bienes y Comercio S.A.",
    valor: 99079915, participacion: 100, fechaInicio: "26/10/2012", fechaFin: "11/01/2013", duracion: "3 meses", smmlv: 174.84,
    imagen: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80",
  },
  {
    id: 75, rupNo: "30",
    title: "ECS 316 de 2012 — Valoración Económica Forestal Quindío",
    year: 2012, type: "Consultoría",
    shortDescription: "Consultoría para la valoración económica de intervención forestal para la Empresa de Energía del Quindío.",
    fullDescription: "Consultoría para la valoración económica de intervención forestal.",
    tag: "Valoración Forestal", color: "#b45309", categoria: "agropecuario",
    entidad: "Empresa de Energía del Quindío",
    valor: 6612000, participacion: 100, fechaInicio: "05/10/2012", fechaFin: "20/10/2012", duracion: "15 días", smmlv: 11.67,
    imagen: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
  },
  {
    id: 76, rupNo: "7",
    title: "Orden de Compra No. 000130 de 2009 — Cámara Climática Universidad Distrital",
    year: 2009, type: "Orden de Compra",
    shortDescription: "Adquisición de equipo de laboratorio — solución integral cámara climática para la Facultad del Medio Ambiente de la Universidad Distrital Francisco José de Caldas.",
    fullDescription: "Adquisición de equipos de laboratorios - Solución integral cámara climática con destino a los Laboratorios, talleres, centros y aulas especializadas de la Facultad del Medio ambiente y Recursos Naturales de la Universidad Distrital Francisco José de Caldas.",
    tag: "Equipos Lab.", color: "#b45309", categoria: "agropecuario",
    entidad: "Universidad Distrital Francisco José de Caldas",
    valor: 45240000, participacion: 100, fechaInicio: "14/09/2009", fechaFin: "14/09/2010", duracion: "1 año", smmlv: 87.84,
    imagen: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80",
  },
  {
    id: 77, rupNo: "37",
    title: "OS 466/2011 — Evaluación Flujos de Agua UMNG",
    year: 2011, type: "Orden de Servicios",
    shortDescription: "Evaluación y caracterización de flujos de agua para la Universidad Militar Nueva Granada.",
    fullDescription: "Evaluación y caracterización de flujos de agua.",
    tag: "Calidad Agua", color: "#b45309", categoria: "agropecuario",
    entidad: "Universidad Militar Nueva Granada",
    valor: 4950000, participacion: 100, fechaInicio: "07/09/2011", fechaFin: "27/09/2011", duracion: "20 días", smmlv: 9.24,
    imagen: "https://images.unsplash.com/photo-1455218873509-8097305ee378?w=600&q=80",
  },
  {
    id: 78, rupNo: "20",
    title: "CPS 106/2013 — Asesoría Normatividad Ambiental Gachetá",
    year: 2013, type: "Prestación de Servicios",
    shortDescription: "Asesoría, acompañamiento y apoyo en el cumplimiento de la normatividad ambiental en el municipio de Gachetá, Cundinamarca.",
    fullDescription: "Prestación de servicios profesionales para la asesoría, acompañamiento y apoyo en el cumplimiento de la normatividad ambiental en el municipio de Gachetá en Cundinamarca.",
    tag: "Normatividad", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 16200000, participacion: 100, fechaInicio: "02/08/2013", fechaFin: "31/12/2013", duracion: "5 meses", smmlv: 27.48,
    imagen: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80",
  },
  {
    id: 79, rupNo: "49",
    title: "Contrato N. 0116 de 2012 — Actualización PGIRS Gachetá",
    year: 2012, type: "Prestación de Servicios",
    shortDescription: "Actualización del plan de Gestión Integral de Residuos Sólidos para el Municipio de Gachetá.",
    fullDescription: "Actualización del plan de Gestión Integral de Residuos Sólidos para el Municipio de Gacheta.",
    tag: "PGIRS", color: "#b45309", categoria: "agropecuario",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 7946000, participacion: 100, fechaInicio: "03/10/2012", fechaFin: "22/12/2012", duracion: "2 meses 19 días", smmlv: 14.02,
    imagen: "https://images.unsplash.com/photo-1492496913980-501348b61469?w=600&q=80",
  },
  {
    id: 80, rupNo: "s",
    title: "Contrato No. 011 — Compensación Campo Opón, Cimitarra",
    year: 2015, type: "Prestación de Servicios",
    shortDescription: "Servicio de desarrollo e implementación de la compensación por cambio de uso de suelo para el campo Opón, Municipio de Cimitarra, Santander.",
    fullDescription: "Realizar y prestar el servicio de desarrollo e implementación de la compensación por cambio de uso de suelo, para el campo Opón, ubicado en el municipio de Cimitarra departamento del Santander.",
    tag: "Compensación", color: "#b45309", categoria: "agropecuario",
    entidad: "Petrocolombia COP", municipio: "Cimitarra, Santander",
    valor: 144319000, participacion: 100, fechaInicio: "01/08/2015", fechaFin: "30/07/2018", duracion: "3 años", smmlv: 223.98,
    imagen: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&q=80",
  },
  {
    id: 81, rupNo: "s",
    title: "Contrato 2048-2014 — Interventoría Humedales Casanare",
    year: 2014, type: "Consultoría",
    shortDescription: "Interventoría técnica, administrativa, financiera y ambiental para estudios de caracterización de Humedales y biodiversidad en ecosistemas del Casanare.",
    fullDescription: "Interventoría Técnica, Administrativa, financiera, contable legal y ambiental, al contrato de consultoría cuyo objeto es, Realizar los estudios de caracterización de Humedales, riqueza de biodiversidad de ecosistemas de piedemonte y montaña, identificación de incentivos socioeconómicos para la conservación y servicios ecosistemicos asociados a adaptación de cambio climático en el departamento de Casanare.",
    tag: "Humedales", color: "#b45309", categoria: "agropecuario",
    entidad: "Gobernación de Casanare", consorcio: "Consorcio Ecocasanare 2014",
    municipio: "Casanare",
    valor: 178396400, participacion: 50, fechaInicio: "12/05/2014", fechaFin: "12/05/2015", duracion: "12 meses", smmlv: 138.32,
    imagen: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&q=80",
  },

  // ═══════════════════════════════════════════
  // TERRITORIAL (8 contratos)
  // ═══════════════════════════════════════════
  {
    id: 82, rupNo: "18",
    title: "Consultoría No. 001 de 2007 — Estudios Técnicos Gachetá",
    year: 2007, type: "Consultoría",
    shortDescription: "Elaboración de estudios técnicos, levantamientos topográficos, avalúos comerciales, gastos de documentación, escrituración y vallas en Gachetá.",
    fullDescription: "Elaboración de estudios técnicos, levantamientos topográficos, avalúos Comerciales, Gastos de Documentación, Escrituración y vallas.",
    tag: "Estudios Técnicos", color: "#6d28d9", categoria: "territorial",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 53928000, participacion: 100, fechaInicio: "27/09/2007", fechaFin: "15/12/2007", duracion: "2 meses 17 días", smmlv: 124.34,
    imagen: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80",
  },
  {
    id: 83, rupNo: "31",
    title: "Prestación de Servicios N° 110 de 2010 — Ruralidad Suba",
    year: 2011, type: "Prestación de Servicios",
    shortDescription: "Red de sociedad civil para articular acciones de gestión y manejo sostenible de zonas de reserva y áreas rurales de la localidad de Suba, Bogotá.",
    fullDescription: "Conformar con los actores involucrados en las anteriores fases de los procesos de ruralidad de áreas protegidas y nuevos actores, una red de la sociedad civil que lidere y articule acciones conducentes al favorecimiento en procesos de gestión para el manejo sostenible de las zonas de reserva y áreas rurales de la localidad de Suba.",
    tag: "Gestión Territorial", color: "#6d28d9", categoria: "territorial",
    entidad: "Alcaldía Local de Suba", municipio: "Suba, Bogotá",
    consorcio: "Consorcio 2C - ECOAFA 2010",
    valor: 219022318, participacion: 50, fechaInicio: "15/02/2011", fechaFin: "30/10/2011", duracion: "8 meses 16 días", smmlv: 408.93,
    imagen: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",
  },
  {
    id: 84, rupNo: "12",
    title: "Consultoría N°8538 — Reciclaje CORANTIOQUIA Suroeste Antioqueño",
    year: 2010, type: "Consultoría",
    shortDescription: "Plan estratégico para fortalecer la red de comercialización regional del reciclaje en 22 municipios del Suroeste antioqueño, jurisdicción de CORANTIOQUIA.",
    fullDescription: "Servicios de consultoría para formular y ejecutar un plan estratégico para fortalecer la red de comercialización regional del Reciclaje de residuos inorgánicos, en 22 municipios del Suroeste antioqueño, jurisdicción de CORANTIOQUIA, analizando los ejes temáticos: técnico-operativo, financiero-comercial, socio-cultural y de seguimiento-evaluación.",
    tag: "Reciclaje", color: "#6d28d9", categoria: "territorial",
    entidad: "CORANTIOQUIA", municipio: "22 municipios Suroeste Antioqueño",
    valor: 220945200, participacion: 100, fechaInicio: "01/02/2010", fechaFin: "12/12/2010", duracion: "11 meses", smmlv: 429.02,
    imagen: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
  },
  {
    id: 85, rupNo: "44",
    title: "Consultoría 2C — Aguas Subterráneas Ubaté y Chiquinquirá",
    year: 2008, type: "Consultoría",
    shortDescription: "Inventario de puntos de agua y cuantificación de la demanda hidráulica subterránea en la zona plana de los valles de Ubaté y Chiquinquirá.",
    fullDescription: "Realizar el inventario de puntos de agua (pozos, aljibes, manantiales) y cuantificación de la demanda hidráulica subterránea en la zona plana de los valles de Ubaté y Chiquinquirá.",
    tag: "Aguas Subterráneas", color: "#6d28d9", categoria: "territorial",
    entidad: "2C Ingenieros S.A.", municipio: "Ubaté y Chiquinquirá",
    valor: 30000000, participacion: 100, fechaInicio: "29/01/2008", fechaFin: "26/09/2008", duracion: "7 meses 15 días", smmlv: 65.01,
    imagen: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80",
  },
  {
    id: 86, rupNo: "59",
    title: "Consultoría No. 269-2014 — PSMV Inspecciones Gachalá",
    year: 2015, type: "Consultoría",
    shortDescription: "Elaboración de estudios y diseños del Plan de Saneamiento y Manejo de Vertimientos de las Inspecciones de Rionegro, Montecristo y los Alpes, Gachalá.",
    fullDescription: "Consultoría para la elaboración de estudios, diseños de los documentos del Plan de Saneamiento y Manejo de Vertimientos-PSMV de las Inspecciones de Rionegro, Montecristo y los Alpes del Municipio de Gachalá, Cundinamarca.",
    tag: "PSMV", color: "#6d28d9", categoria: "territorial",
    entidad: "Alcaldía Municipal de Gachalá", municipio: "Gachalá, Cundinamarca",
    valor: 49402080, participacion: 100, fechaInicio: "07/01/2015", fechaFin: "06/04/2015", duracion: "3 meses 19 días", smmlv: 76.67,
    imagen: "https://images.unsplash.com/photo-1519011985664-040dd7d27db7?w=600&q=80",
  },
  {
    id: 87, rupNo: "70",
    title: "Consultoría No. 200-12-4-292 de 2015 — Ruta del Agua Guavio",
    year: 2015, type: "Consultoría",
    shortDescription: "Diseño e implementación de la 'RUTA DEL AGUA' en Guasca, Junín, Gachetá, Ubalá y Gachalá para el desarrollo del turismo sostenible en la provincia del Guavio.",
    fullDescription: "Realizar el diseño e implementación del producto turístico la 'RUTA DEL AGUA' en los municipios de Guasca, Junín, Gachetá, Ubalá y Gachalá, con el fin de orientar la riqueza natural y cultural de la provincia del Guavio hacia el desarrollo de un turismo sostenible, con visión regional en una perspectiva de mitigación orientada hacia el cambio climático.",
    tag: "Turismo Sostenible", color: "#6d28d9", categoria: "territorial",
    entidad: "CORPOGUAVIO", municipio: "Provincia del Guavio",
    consorcio: "Consorcio Ruta del Agua 2015",
    valor: 849120000, participacion: 55, fechaInicio: "20/08/2015", fechaFin: "13/07/2016", duracion: "12 meses", smmlv: 1231.58,
    imagen: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=600&q=80",
  },
  {
    id: 88, rupNo: "9",
    title: "Prestación de Servicios No. 014 de 2007 — Interventoría Reforestación Gachetá",
    year: 2008, type: "Interventoría",
    shortDescription: "Interventoría técnica para el contrato de reforestación protectora a nacimientos de agua de la cabecera municipal y áreas ribereñas del Municipio de Gachetá.",
    fullDescription: "Interventoría Técnica para el contrato de implantación de Reforestación protectora a nacimientos de Agua que abastecen la cabecera municipal y áreas ribereñas del Municipio de Gachetá, Departamento de Cundinamarca.",
    tag: "Interventoría", color: "#6d28d9", categoria: "territorial",
    entidad: "Alcaldía Municipal de Gachetá", municipio: "Gachetá, Cundinamarca",
    valor: 24457397, participacion: 100, fechaInicio: "11/02/2008", fechaFin: "10/02/2009", duracion: "12 meses", smmlv: 49.22,
    imagen: "https://images.unsplash.com/photo-1510218830377-2e994ea9bc6e?w=600&q=80",
  },
  {
    id: 89, rupNo: "94",
    title: "Consultoría No. 194 de 2017 — Estrategia de Respuesta Municipal La Vega",
    year: 2018, type: "Consultoría",
    shortDescription: "Actualizar la estrategia de respuesta municipal de acuerdo con la Ley 1523 de 2012 en el municipio de La Vega, Cundinamarca.",
    fullDescription: "Actualizar la estrategia de respuesta municipal de acuerdo con la Ley 1523 de 2012 en el municipio de La Vega - Cundinamarca.",
    tag: "Gestión del Riesgo", color: "#6d28d9", categoria: "territorial",
    entidad: "Alcaldía Municipal de La Vega", municipio: "La Vega, Cundinamarca",
    valor: 40251750, participacion: 100, fechaInicio: "10/01/2018", fechaFin: "09/06/2018", duracion: "5 meses", smmlv: 142.68,
    imagen: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&q=80",
  },
];